# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
      timezone: 'Asia/Shanghai'
    open-pull-requests-limit: 10
    target-branch: 'dev'
    allow:
      - dependency-name: '@emotion/react'
      - dependency-name: '@emotion/styled'
      - dependency-name: '@fontsource/barlow'
      - dependency-name: '@mui/material'
      - dependency-name: '@mui/system'
      - dependency-name: 'ahooks'
      - dependency-name: 'byte-size'
      - dependency-name: 'electron-store'
      - dependency-name: 'electron-updater'
      - dependency-name: 'i18next'
      - dependency-name: 'jotai'
      - dependency-name: 'lodash'
      - dependency-name: 'query-string'
      - dependency-name: 'react'
      - dependency-name: 'react-dom'
      - dependency-name: 'react-i18next'
      - dependency-name: 'react-router-dom'
      - dependency-name: '@types/byte-size'
      - dependency-name: '@types/jest'
      - dependency-name: '@types/lodash'
      - dependency-name: '@types/react'
      - dependency-name: '@types/react-dom'
      - dependency-name: '@types/react-test-renderer'
      - dependency-name: 'electron'
      - dependency-name: 'electron-builder'
      - dependency-name: 'electron-devtools-installer'
      - dependency-name: 'react-test-renderer'
