'append_commit_message': true
'commit_message': 'fix: new translations %three_letters_code% from Crowdin'

files:
  - source: /src/renderer/i18n/locales/en.json
    translation: /src/renderer/i18n/locales/%three_letters_code%.json
