name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish_outside:
    name: Publish Outside
    if: ${{ github.repository_owner == 'shensven' }}

    runs-on: ${{ matrix.os }}

    env:
      # These values are used for auto updates signing
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      # This is used for uploading release assets to github
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Rewritten buildVersion
        run: |
          npx -y json -I -f build/electron.common.json -e "this.buildVersion=${{ github.run_number }}"

      - name: Install dependencies
        run: |
          npm install

      - name: Releases
        run: |
          npm run postinstall
          npm run build
          npm run release:outside

  publish_app_store:
    name: Publish App Store
    if: ${{ github.repository_owner == 'shensven' }}

    runs-on: ${{ matrix.os }}

    env:
      # These values are used for auto updates signing
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      # This is used for uploading release assets to github
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Rewritten buildVersion
        run: |
          npx -y json -I -f build/electron.common.json -e "this.buildVersion=${{ github.run_number }}"

      - name: Restore provisionprofile
        run: |
          cd build
          echo "${{ secrets.EMBEDDED_PROVISIONPROFILE_ASC }}" > embedded.provisionprofile.asc
          gpg -d --passphrase ${{ secrets.EMBEDDED_PROVISIONPROFILE_PASSPHRASE }} --batch embedded.provisionprofile.asc > embedded.provisionprofile

      - name: Install dependencies
        run: |
          npm install

      - name: Releases
        run: |
          npm run postinstall
          npm run build
          npm run release:mas

      - name: Upload app store
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: app-store
          tag: app-store
          allowUpdates: true
          draft: true
          artifacts: 'release/build/mas/*.pkg'
