name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    if: ${{ github.repository_owner == 'shensven' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Rewritten buildVersion
        run: |
          npx -y json -I -f package.json -e "this.build.buildVersion=${{ github.run_number }}"

      - name: Restore provisionprofile
        run: |
          cd build
          echo "${{ secrets.EMBEDDED_PROVISIONPROFILE_ASC }}" > embedded.provisionprofile.asc
          gpg -d --passphrase ${{ secrets.EMBEDDED_PROVISIONPROFILE_PASSPHRASE }} --batch embedded.provisionprofile.asc > embedded.provisionprofile

      - name: Install dependencies
        run: |
          npm install

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run postinstall
          npm run build
          npm exec electron-builder -- --publish always --win --mac --linux
